---
- name: Removing PVs
  hosts: localhost
  become: false
  gather_facts: false
  module_defaults:
    group/redhat.openshift.openshift:
      validate_certs: false
    group/kubernetes.core.k8s:
      validate_certs: false

  vars:
    storageclass: iscsi-blk

  tasks:
    - name: Retrieve the PVs
      kubernetes.core.k8s_info:
        kind: PersistentVolume
      register: pvs

    - name: Ensure the PVs are removed
      redhat.openshift.k8s:
        state: absent
        resource_definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: "{{ item['metadata']['name'] }}"
      when: item['spec']['storageClassName'] == storageclass
      loop: "{{ pvs['resources'] }}"

    - name: Ensure the storage class is removed
      redhat.openshift.k8s:
        state: absent
        resource_definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: "{{ storageclass }}"
...
